#!/usr/bin/env python3

import letters as le
import json
import sys

def load_game():
    with open('letters.json', 'r') as pfile:
        j=json.load(pfile)
        #le.Letter.a=j['a']
    inverse = {y:x for x,y in j.items()}
    encodedmessage = input("What is your encoded message? >> ")
    n=0
    while n < len(encodedmessage):
        sys.stdout.write(inverse[encodedmessage[n]])
        n += 1
    print("")

if __name__=='__main__':
    load_game()
