#!/usr/bin/env python3

import letters as le
import json
import sys
import skilstak.colors as c
from os import system

def encoder():
    with open('letters.json', 'r') as pfile:
        j=json.load(pfile)
        #le.Letter.a=j['a']
    n=0
    final = "#"
    message = input(c.clear + c.red + "What is your message? >> " + c.orange)
    while n < len(message):
        final += j[message[n]]
        n += 1
    print(c.orange + final)
    system('''echo 'text = "''' + final + '''"' >> message.py''')

if __name__=='__main__':
    encoder()
