#!/usr/bin/env python3

import letters as le
import json
import sys

def encoder():
    with open('letters.json', 'r') as pfile:
        j=json.load(pfile)
        #le.Letter.a=j['a']
    n=0
    message = input("What is your message? >> ")
    while n < len(message):
        sys.stdout.write(j[message[n]])
        n += 1
    print("")

if __name__=='__main__':
    encoder()
