#!/usr/bin/env python3
 
import skilstak.colors as c
import urllib.request
import json
from os import system
from time import sleep
import random

with urllib.request.urlopen('https://rawgit.com/colevahey/miniature-enigma/master/letters.json') as web:
    onlinejson = web.read()
    data = json.loads(onlinejson.decode("utf-8"))

with open('letters.json') as local:
    localdata = json.load(local)

def checker():
    if data == localdata:
        print(c.clear + c.green + "The code is up to date" + c.x)
    else:
        print(c.clear + c.red + "The code is not up to date\n")
        pushorpull = input("Would you like to push your version of the code or pull the online version of the code?\n" + c.x + "Note: There is latency when updating the github raw code\n>> " + c.red)
        if pushorpull.lower().strip() == "push":
            system('save')
        elif pushorpull.lower().strip() == "pull":
            system('git pull')
        else:
            print("That is not an acceptable input please try again" + c.x)
            sleep(1.5)
            checker()

if __name__ == '__main__':
    try:
        checker()
    except KeyboardInterrupt:
        print()
        exit()
