#!/usr/bin/env python3
 
import skilstak.colors as c
import random
from sys import argv
from os import system

def ask_message():
    message = input("What is your message? >> ")
    rot(message)

def rot(message):
    charcount = random.randint(0,95)
    if not message.startswith("*"):
        final = "*" + str(charcount)
        for c in message:
            newchr = ord(c) + charcount
            if newchr > 126:
                newchr -= 95
            elif ord(c) < 32:
                print("That character is not supported")
            else:
                pass
            final += chr(newchr)
        print(final)
    else:
        final = ""
        charcount = int(message[1] + message[2])
        nmessage = message[3:]
        for c in nmessage:
            newchr = ord(c) - charcount
            if newchr < 32:
                newchr += 95
            else:
                pass
            final += chr(newchr)
        print(final)

if __name__ == '__main__':
    if len(argv) == 1:
        ask_message()
    elif len(argv) == 2:
        if argv[1] == '-m':
            print("You need to include a message")
        elif argv[1] == '-e':
            #encode
            pass
        elif argv[1] == '-d':
            #decode
            pass
        elif argv[1] == '-h':
            #help
            pass
        else:
            print("That input is not acceptable. To view help type 'rot -h'")
    elif len(argv) == 3:
        if argv[1] == '-m':
            rot(argv[2])
            #strip function will strip the quotations off prior to encoding/decoding
        else:
            print("That input is not acceptable. To view help type 'rot -h'")
    else:
        if argv[1] == '-m':
            print("Surround your message in quotes to use the '-m' option")
        else:
            print("That input is not acceptable. To view help type 'rot -h'")
