#!/usr/bin/env python3
 
import skilstak.colors as c
import random
from sys import argv

def rot(charcount):
    message = input("What is your message? >> ")
    if not message.startswith("#"):
        final = str(charcount) + "#"
        for c in message:
            newchr = ord(c) + charcount
            if newchr > 126:
                newchr -= 95
            elif ord(c) < 32:
                print("That character is not supported")
            else:
                pass
            final += chr(newchr)
        print(final)
    #If the message starts with # or is encoded
    else:
        final = ""
        nmessage = message[1:]
        for c in nmessage:
            newchr = ord(c) - charcount
            if newchr < 32:
                newchr += 95
            else:
                pass
            final += chr(newchr)
        print(final)

if __name__ == '__main__':
    if len(argv) == 1:
        rot(random.randint(0,95))
    elif len(argv) == 2:
        print("Oops")
        
