#!/usr/bin/env python3
 
import colors as c
import random
from sys import argv
from os import system

def randomnumber():
    return random.randint(0,95)

def fixer(num):
    if int(num) > 95 or int(num) < 0:
        print("Please input a number between 0 and 95")
    elif int(num) < 10:
        charcount = "0" + str(num)
    else:
        charcount = str(num)
    return charcount

def ask_message():
    message = input("What is your message? >> ")
    return message

def rot(message, charcount):
    if not message.startswith("#"):
        final = "#" + str(charcount)
        for c in message:
            newchr = ord(c) + int(charcount)
            if newchr > 126:
                newchr -= 95
            elif ord(c) < 32:
                print("That character is not supported")
            else:
                pass
            final += chr(newchr)
        print(final)
    else:
        final = ""
        charcount = int(message[1] + message[2])
        nmessage = message[3:]
        for c in nmessage:
            newchr = ord(c) - int(charcount)
            if newchr < 32:
                newchr += 95
            else:
                pass
            final += chr(newchr)
        print(final)

if __name__ == '__main__':
    message = None
    key = None
    for arg in range(len(argv)):
        if argv[arg] in __file__:
            pass
        elif argv[arg] == '-m':
            message = argv[arg+1]
        elif argv[arg] == '-k':
            key = argv[arg+1]
        else:
            pass
    if message == None and key == None:
        print("No message and no key")
        rot(ask_message(),fixer(randomnumber()))
    elif not message == None and key == None:
        print("Message but no key")
        rot(message,fixer(randomnumber()))
    elif message == None and not key == None:
        print("No message but a key")
        rot(ask_message(),fixer(key))
    else:
        rot(message,fixer(key))
