#!/usr/bin/env python3
 
import skilstak.colors as c
from sys import argv

def testit(message,key):
    print("MESSAGE: " + message + " KEY: " + str(key))

if __name__ == '__main__':
    message = "None"
    key = 0
    for arg in range(len(argv)):
        if argv[arg] in __file__:
            pass
        elif argv[arg] == '-m':
            message = argv[arg+1]
        elif argv[arg] == '-k':
            key = argv[arg+1]
        else:
            pass
    testit(message,key)
